import Head from "next/head";
import Footer from "./footer";
import Sidebar from "./Sidebar";
import PageHeader from "./PageHeader";
import { useState, useEffect } from "react";
import React from "react";

const Page = ({ title, subtitle, children, searchValue, onSearchChange, showSearch, breadcrumb, onBreadcrumbClick }) => {
    const [isCollapsed, setIsCollapsed] = useState(false);

    useEffect(() => {
        const savedState = localStorage.getItem('sidebarCollapsed');
        if (savedState !== null) {
            const collapsed = JSON.parse(savedState);
            setIsCollapsed(collapsed);
        }
    }, []); // Only run on mount

    const handleSidebarCollapse = (collapsed) => {
        setIsCollapsed(collapsed);
    };

    return (
        <>
            <Head>
                <title>{title} discrimin8r</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex min-h-screen bg-[#F3F3FF]">
                <Sidebar onCollapse={handleSidebarCollapse} />
                <main
                    className={`flex-1 ${isCollapsed ? 'ml-16' : 'ml-64'} min-h-screen flex flex-col`}
                    style={{
                        width: isCollapsed ? 'calc(100% - 4rem)' : 'calc(100% - 16rem)',
                        maxWidth: '100%'
                    }}
                >
                    <div className="flex-1 px-12 py-6">
                        <PageHeader
                            title={title}
                            subtitle={subtitle}
                            searchValue={searchValue}
                            onSearchChange={onSearchChange}
                            showSearch={showSearch}
                            breadcrumb={breadcrumb}
                            onBreadcrumbClick={onBreadcrumbClick}
                        />
                        {React.Children.map(children, child =>
                            React.isValidElement(child)
                                ? React.cloneElement(child, { isCollapsed })
                                : child
                        )}
                    </div>
                    <Footer />
                </main>
            </div>
        </>
    );
};

export default Page;
