import Head from "next/head";
import Footer from "./footer";
import Sidebar from "./Sidebar";
import PageHeader from "./PageHeader";
import { useState, useEffect } from "react";
import React from "react";
import MobileView from "./MobileView";

const Page = ({ title, subtitle, children, searchValue, onSearchChange, showSearch, breadcrumb, onBreadcrumbClick }) => {
    const [isCollapsed, setIsCollapsed] = useState(false);
    const [isTransitioning, setIsTransitioning] = useState(false);
    const [hydrated, setHydrated] = useState(false);
    const [isMobile, setIsMobile] = useState(false);

    useEffect(() => {
        // Set initial mobile state based on window width
        if (typeof window !== 'undefined') {
            setIsMobile(window.innerWidth < 768);
        }
        setHydrated(true);

        const savedState = localStorage.getItem('sidebarCollapsed');
        if (savedState !== null) {
            const collapsed = JSON.parse(savedState);
            setIsCollapsed(collapsed);
        }

        const checkIfMobile = () => {
            setIsMobile(window.innerWidth < 768);
        };

        // Add resize listener
        window.addEventListener('resize', checkIfMobile);

        // Cleanup
        return () => {
            window.removeEventListener('resize', checkIfMobile);
        };
    }, []); // Empty dependency array

    const handleSidebarCollapse = (collapsed) => {
        setIsTransitioning(true);
        setIsCollapsed(collapsed);
        // Remove transition after animation completes
        setTimeout(() => setIsTransitioning(false), 300);
    };

    // Don't render anything during SSR
    if (typeof window === 'undefined') return null;

    // Don't render until mounted
    if (!hydrated) return null;

    // Return mobile view if on mobile
    if (isMobile) {
        return <MobileView />;
    }

    return (
        <>
            <Head>
                <title>{hydrated ? (typeof title === 'string' ? `${title} discrimin8r` : 'discrimin8r') : 'discrimin8r'}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex min-h-screen bg-[#F3F3FF]">
                <Sidebar onCollapse={handleSidebarCollapse} />
                <main
                    className={`flex-1 ${isCollapsed ? 'ml-16' : 'ml-64'} min-h-screen flex flex-col ${isTransitioning ? 'transition-all duration-300 ease-in-out' : ''}`}
                    style={{
                        width: isCollapsed ? 'calc(100% - 4rem)' : 'calc(100% - 16rem)',
                        maxWidth: '100%'
                    }}
                >
                    <div className="flex-1 px-12 py-6">
                        <PageHeader
                            title={title}
                            subtitle={subtitle}
                            searchValue={searchValue}
                            onSearchChange={onSearchChange}
                            showSearch={showSearch}
                            breadcrumb={breadcrumb}
                            onBreadcrumbClick={onBreadcrumbClick}
                        />
                        {React.Children.map(children, child =>
                            React.isValidElement(child) && typeof child.type === 'function'
                                ? React.cloneElement(child, { isCollapsed })
                                : child
                        )}
                    </div>
                    <Footer />
                </main>
            </div>
        </>
    );
};

export default Page;
